### ISSUE TITLE
2D / 3D - Map concepts

### ISSUE THREAD

**Issue by Cek4y** [kellergemeinde/game_towerdefense#117]
For better visualisation we need first concepts of the main map.

For technical requirements refer to the GDD please, e.g. "How many lanes does the map need".

**Comment by 0dr** [comment]
![konzept1_hand](https://user-images.githubusercontent.com/295577/35048730-3132cb16-fb9e-11e7-89fd-5edafd6e36d1.jpg)

![konzept1](https://user-images.githubusercontent.com/295577/35048745-3a9492de-fb9e-11e7-9f5a-e40f581020a1.jpg)

1.  coal mine / old n' busted elevator with minimal safety for its passenger   
2. Pipes blow out (+) a bridge goes across to allow units passing. the bridge has a wide criss cross base to "allow" the (+) to "flow" thou 
3.  Simple security gates, they need their own poles to support the gate (not attached to surroundings because train)  
4.  Train tracks all over the board cus its an industrial plant and such.  
5.  Different Pipes caged in supporting structures, doing bends and loops attaching to the (+) pipe.  A large variety would allow for random pipe placement 
6.  The Pipes get redirected up / downwards and lead out of the map. downside is that the topview would get blocked by too many pipes -> maybe we can have a function that allows to hide part of the map geometry if units are below  
7. The towers would be placed atop the pipe support structures, they shouldn't bee too high because the base itself is already.

**thoughts / need discussion:**
I wonder how difficult it would be if we allow the placement of pipe / train (walls)  to be randomly generated. 
If not, I am unsure about the placement of pipe / train walls, the perfect 50/50 feels wrong but all trains to one side / more pipes does too..

**Comment by 0dr** [comment]
Theme:  I tent more to the rusty old themed industrial plant:  
![img1](http://ak2.picdn.net/shutterstock/videos/1038712/thumb/1.jpg)
![img2](http://www.watertowers.com/uploads/183350387_aeea333b43.jpg)

Additional: 

The map(env) doesn't have to be symmetrical, one side could be the main building with the pipes leading to it while the other has more rails and rail related buildings leading up to the main complex.

![](http://www.bahnbilder.de/bilder/abstellgleise-betriebshof-muenchener-u-bahn-froettmaning-97026.jpg)

**Comment by xdubx** [comment]
![level-1](https://user-images.githubusercontent.com/23421736/35196243-c4008882-fecf-11e7-86e6-d16e26db5f6d.png)

![level-2](https://user-images.githubusercontent.com/23421736/35196245-c63ca324-fecf-11e7-86da-ed9cc867d25d.png)

find at https://github.com/xdubx/pictures/blob/master/level-1.png
https://github.com/xdubx/pictures/blob/master/level-2.png

reference pictures:
![39046458-cyberpunk-wallpapers](https://user-images.githubusercontent.com/23421736/35196272-0b3948c4-fed0-11e7-971f-52e899b665be.jpg)

![38719061-cyberpunk-wallpapers](https://user-images.githubusercontent.com/23421736/35196273-1027db52-fed0-11e7-951b-ad9703101a56.jpg)

![69e8c9f8664e8306fd7d1a289be04f4b](https://user-images.githubusercontent.com/23421736/35196281-19ef4ed6-fed0-11e7-93e6-f380c0e7df6c.jpg)

![4f3e1213ac675830d62d9fe084889139](https://user-images.githubusercontent.com/23421736/35196277-151ccbf4-fed0-11e7-99f1-12779489c08f.jpg)

**Comment by xdubx** [comment]
# Coole Notizen
**Low Poli** 
Greifarme müssen genug vorhanden. Eine Zeit definieren wie lange die Ressource vorhanden ist damit der Kran die schnell genug herstellen kann? Timer ??

Walls sollten Radom generiert werden.
Anforderung: Wenn jede Wall Points generieren soll  statt den Kran. 
Z.B 

- Ein Schließfach aus dem es raus fliegt

- Oder eine Drohne einfliegen. 

- Wall 1 hat ein Leck. Energie läuft aus und spawned  die Box.


- Wall 3 mit Förderband. Daraus fällt dann Plus raus. 

Wenn die Wände Points spawnen soll der Kran weg!
-> Alles was über dem Spielfeld ist und die Sicht verdeckt soll weg. 
Gebäude sind zu groß. -> Diese sollen halbdurchsichtig werden, oder nur den Ansatz reduzieren.
Aufzugschacht  -> Tiefe Grube in die Rohre rein laufen mit Dreck usw.
Punkte Tank soll gebaut werden.
(War afk....)
Lichtschranke für die Barriere. Rohre laufen vom Tank dorthin. 
Wand Set entwickeln. Mit Verschiedenen Variationen.  Jeder Artist macht sein eigenes mit der Vorlage. 
Wände sind so 2/3 so breit wie die Lane? Wände Größe undefiniert.
Länge der Lane klären. Seitenverhältnisse mit Bildmaterial herausfinden. 
Lanes sollen länger sein als die Spawn Arena! 
Die Bezugs Größen müssen geklärt.

**Comment by 0dr** [comment]
As I see it what is left to do:

- [ ] get a feeling(decide) for the aspect ratio between lane / wall width 
- [ ] aspect ratio lane / base(spawn area) length  
- [ ] quick 3d mockup (we can skip this if lead has a good grasp of the concept)
- [ ] have lead confirm (vote?) for this concept

**Comment by Cek4y** [comment]
Great work!

Until the planned game prototype is done and working, we should freeze this to not waste any work.

But so far it's a **go** on all aspects.

**Comment by ulfgebhardt** [comment]
@Cek4y Review und Doku bitte

**Comment by Cek4y** [comment]
Done, moving to 3D phase
